name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release styles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compress styles
        run: tar -czvf styles.tar.gz base default fa-grid

      - name: Releasing assets
        uses: softprops/action-gh-release@v2
        with:
          files: styles.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
